language: swift
osx_image: xcode8.3

before_install:
    - pod --version
    - pod setup --silent
    - pod repo update --silent
    
script:
    - pod lib lint
    - xcodebuild -project Demo/InjectStory.xcodeproj | xcpretty
