language: swift
osx_image: xcode12

before_install:
    - pod --version
    
script:
    - pod lib lint
    - xcodebuild test -project Demo/InjectStory.xcodeproj -scheme InjectStoryTests -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty
